# Generated by Django 3.0.2 on 2020-01-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('stdate', models.CharField(max_length=20)),
                ('stcoord', models.CharField(max_length=100)),
                ('stsurname', models.CharField(max_length=100)),
                ('sthost', models.CharField(max_length=100)),
                ('stname', models.CharField(max_length=50)),
                ('st1', models.CharField(max_length=20)),
                ('st1a', models.TextField(blank=True)),
                ('st2', models.TextField(blank=True)),
                ('st3', models.TextField(blank=True)),
                ('st4', models.CharField(max_length=10)),
                ('st4a', models.TextField(blank=True)),
                ('st4b', models.TextField(blank=True)),
                ('st5', models.CharField(max_length=10)),
                ('st5a', models.TextField(blank=True)),
                ('st6', models.CharField(max_length=20)),
                ('st6a', models.TextField(blank=True)),
                ('st6b', models.TextField(blank=True)),
                ('st7', models.CharField(max_length=10)),
                ('st7a', models.CharField(max_length=10)),
                ('st7b', models.TextField(blank=True)),
                ('stcomments', models.TextField(blank=True)),
                ('hfname', models.CharField(max_length=100)),
                ('hf1', models.CharField(max_length=20)),
                ('hf1a', models.TextField(blank=True)),
                ('hf2', models.TextField(blank=True)),
                ('hf3', models.CharField(max_length=10)),
                ('hf3a', models.TextField(blank=True)),
                ('hf3b', models.TextField(blank=True)),
                ('hf4', models.CharField(max_length=10)),
                ('hf4a', models.TextField(blank=True)),
                ('hf4b', models.TextField(blank=True)),
                ('hf5', models.CharField(max_length=10)),
                ('hf5a', models.TextField(blank=True)),
                ('hf6', models.CharField(max_length=10)),
                ('hf6a', models.TextField(blank=True)),
                ('hf7', models.CharField(max_length=20)),
                ('hf7a', models.TextField(blank=True)),
                ('hfcomments', models.TextField(blank=True)),
                ('schname', models.CharField(max_length=50)),
                ('schstudent', models.CharField(max_length=100)),
                ('sch1a', models.CharField(max_length=100)),
                ('sch1b', models.TextField(blank=True)),
                ('sch2', models.CharField(max_length=20)),
                ('sch2a', models.TextField(blank=True)),
                ('sch3', models.CharField(max_length=10)),
                ('sch3a', models.TextField(blank=True)),
                ('sch4', models.CharField(max_length=10)),
                ('sch4a', models.IntegerField(default=0)),
                ('sch4b', models.CharField(max_length=10)),
                ('sch4c', models.TextField(blank=True)),
                ('sch5', models.CharField(max_length=10)),
                ('sch5a', models.CharField(max_length=100)),
                ('sch6', models.CharField(max_length=10)),
                ('sch6a', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
